language: php
php:
  - 5.5
  - 5.4
  - hhvm
before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - git clone https://git.wikimedia.org/git/mediawiki/tools/codesniffer.git /home/travis/build/codesniffer
script:
  - phpcs . --standard=/home/travis/build/codesniffer/MediaWiki/ruleset.xml --ignore=home.php
  - phpunit tests
