dist: trusty
sudo: false
group: beta
language: php
php:
  - 7.0
  - hhvm
before_script:
  - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi
  - composer install
script: composer test
